### ISSUE TITLE
compatibility ezviz c6c

### ISSUE THREAD

**Issue by thetux07** [BaQs/pyEzviz#1]
Hello,
it's compatible with ezviz c6c caméra ? or it's just compatible with an ezwiz camera with an http interface ?
thank you
regards

**Comment by thetux07** [comment]
Bonjour,
j'ai testé et ma caméra est bien compatible,
peut on avoir accés a autre chose qu'au streaming ? genre le capteur de présence ? 
il y a t'il une carte LOVELACE de prévu pour ça ?
merci

**Comment by virtualgeek84** [comment]
I have Ezviz C3W (Husky) Camera's and am struggling to get them to work:

This is the log:

Error while setting up ezviz platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ezviz/camera.py", line 50, in setup_platform
    cameras = ezviz_client.load_cameras()
  File "/usr/local/lib/python3.7/site-packages/pyezviz/client.py", line 197, in load_cameras
    cameras.append(camera.status())
  File "/usr/local/lib/python3.7/site-packages/pyezviz/camera.py", line 97, in status
    'follow_move': self._switch[TYPE_FOLLOW_MOVE]['enable'],
KeyError: 25

**Comment by BaQs** [comment]
> 
> Bonjour,
> j'ai testé et ma caméra est bien compatible,
> peut on avoir accés a autre chose qu'au streaming ? genre le capteur de présence ?
> il y a t'il une carte LOVELACE de prévu pour ça ?
> merci

The lovelace card is here:

https://www.home-assistant.io/integrations/ezviz/

**Comment by BaQs** [comment]
> 
> 
> I have Ezviz C3W (Husky) Camera's and am struggling to get them to work:
> 

Your camera does not seem to support "follow move" feature.
Do you confirm that v 0.1.5.5 works for you ?

**Comment by thetux07** [comment]
hello,
my camera is equipped "folow move" but it don't work with your component 
juste the streaming work...
it's normal?

**Comment by RenierM26** [comment]
Hi All,

The follow move switch has been fixed in last few versions. I'l closing this issue to cleanup the issues list.

You're more than welcome to open a new issue if your're still having difficulty.
