### ISSUE TITLE
Wake up a battery Cam (C3a)

### ISSUE THREAD

**Issue by rezzalex** [BaQs/pyEzviz#107]
Hello,

I have tried this command with no success  :  

> root@xxxxxx:/opt/domoticz# pyezviz -u login -p pass camera --serial xxxxxxxxx switch --switch sleep --enable 1
> Could not set the switch: Got 200 : {"meta":{"code":2009,"message":"设备网络异常,请检查设备网络或者重试","moreInfo":null}})
> root@xxxxxx:/opt/domoticz# ^C
> root@xxxxxx:/opt/domoticz# pyezviz -u login -p pass camera --serial xxxxxxxxx switch --switch sleep --enable 0
> Could not set the switch: Got 200 : {"meta":{"code":2009,"message":"设备网络异常,请检查设备网络或者重试","moreInfo":null}})

what would be the correct syntax ?
The idea would be to be able to stream the video flow from Domoticz, as a "standard" cam

**Comment by rezzalex** [comment]
I think I have succeed to pass the command.
But it seems to completely put the Cam in hibernation, ans then impossible to wake it up... except physically

**Comment by RenierM26** [comment]
Hi @rezzalex,

Easiest way to wake the camera is by querying detection sensitivity (The command is forwarded directly to the device)

**Comment by rezzalex** [comment]
Thank you @RenierM26 , could you detail the command to do that ?

**Comment by RenierM26** [comment]
Hi @rezzalex,

Setting the camera detection sensitivity with the --sensibility switch should do the trick. Should still work even if you set it to the same level as what it 's currently. (0 - 100 for PIR cameras like the C3A)

**Comment by rezzalex** [comment]
This is working, thank you. Sensibility values are from 1 to 6
