### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by fabaff** [BaQs/pyEzviz#13]
Please add a `LICENSE` file that contains the content of the used license.

This is a requirement for a lot of distributions. The review for the Fedora Package Collection may fails if licensing is not clean. Thus it's highly recommended to add the version number of the license as well (ASL 2.0?).

**Comment by fabaff** [comment]
README: MIT https://github.com/BaQs/pyEzviz#license
setup.py: ASL https://github.com/BaQs/pyEzviz/blob/master/setup.py#L9

**Comment by BaQs** [comment]
Hi Fabaff,

License is ASL 2.0, and clarified everywhere.

Do you plan integrating the library within Fedora ?

**Comment by fabaff** [comment]
> Do you plan integrating the library within Fedora ?

It's still on the list. But there is not ETA.
