### ISSUE TITLE
Privacy / Standby Mode for camera

### ISSUE THREAD

**Issue by OOZAER** [BaQs/pyEzviz#14]
Hello,

It a very good jobs.

As I prefer PHP (to create a plugin for jeedom), I rewrote your scripts.
During my tests, I found a little mistake :
On line 4 in camera.py, you set ` TYPE_PRIVACY_MODE = 21`.
21 is for standby Mode on my CS-CV246 camera.
If I set TYPE_PRIVACY_MODE to 7, my camera switches to correct privacy mode (the eye of the camera turns completely).

Best regards

**Comment by BaQs** [comment]
I believe this issue has been fixed in 0.1.5.7 version, thanks to fixes from RenierM26.

Could you please confirm ?

**Comment by RenierM26** [comment]
Hi All,

The privacy mode setting has been fixed in last few versions. I'l closing this issue to cleanup the issues list.

You're more than welcome to open a new issue if your're still having difficulty.
