### ISSUE TITLE
Setting Alarm Notify on or off is failing

### ISSUE THREAD

**Issue by JongsmaSimon** [BaQs/pyEzviz#15]
I have 4 EzViz camera's. For each camera a status line is shown correctly after doing:
pyezviz -u em@il -p PASS devices status

Most allowed statements do work, but not setting Alarm Notify; on adding --debug it shows error as below:
pyezviz -u em@il -p PASS --debug camera --serial xxxxxxxxx alarm --notify 1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): apiieu.ezvizlife.com:443
send: b'POST /v3/users/login HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1464.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Type: application/x-www-form-urlencoded\r\nclientType: 1\r\ncustomNo: 1000001\r\nContent-Length: 120\r\n\r\n'
send: b'account=em@il&password=xxxxxxxx&featureCode=92c579faa0902cbfcfcc4fc004ef67e7'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Encoding: gzip
header: Content-Type: application/json;charset=UTF-8
header: Date: Sun, 18 Oct 2020 21:52:38 GMT
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 519
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "POST /v3/users/login HTTP/1.1" 200 519
DEBUG:root:Camera loaded
enable: 1, operationType: 1
send: b'POST /api/other/data/report HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1464.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Length: 202\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'clientType=1&infoDetail=%7B%22operationType%22%3A1%2C%22detail%22%3A%220%22%2C%22deviceSerial%22%3A%22E11264168%2C2%22%7D&infoType=3&netType=WIFI&requestType=0&sessionId=756ac850c2bd46268d4fa6c72fd6fdcf'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Content-Encoding: gzip
header: Content-Type: application/json;charset=UTF-8
header: Date: Sun, 18 Oct 2020 21:52:41 GMT
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 132
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "POST /api/other/data/report HTTP/1.1" 404 132
send: b'POST /api/device/configAlgorithm HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1464.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Length: 77\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'subSerial=E11264168&type=0&sessionId=756ac850c2bd46268d4fa6c72fd6fdcf&value=3'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Access-Control-Allow-Headers: Content-Type, api_key, Authorization
header: Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
header: Access-Control-Allow-Origin: *
header: Cache-Control: no-cache, must-revalidate
header: Content-Encoding: gzip
header: Content-Language: en
header: Content-Type: text/html;charset=utf-8
header: Date: Sun, 18 Oct 2020 21:52:41 GMT
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 456
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "POST /api/device/configAlgorithm HTTP/1.1" 400 456

**Comment by scavenrage** [comment]
Exactly the same result for me!

**Comment by Mallinanga** [comment]
same here

**Comment by Mallinanga** [comment]
I think the problem might be on some cameras where the ezDeviceCapability property is empty.
I managed to pinpoint that this error appears only on one of my cameras where ezDeviceCapability is empty.
On the other cameras I get no error.

Maybe this will be of some help to the developer.

**Comment by RenierM26** [comment]
Hi All,

This works in the latest version. I'm busy closing old issues.
