### ISSUE TITLE
Support for EZVIZ DB1

### ISSUE THREAD

**Issue by GrumpyMeow** [BaQs/pyEzviz#3]
Hi, 

I own an [EZVIZ DB1 doorbell](https://www.ezvizlife.com/product/db1/960). Although it's really good piece of hardware, it was only possible to integrate a simple RTSP stream into Home Assistant.
Your package gives an oppening to get more functionality into Home Assistant.

I did some debugging and found out that the following code is limitiing it to work:
1. I commented out the "deviceCategory"-check. As the DB1 identifies itself as a "BDoorBell".
    ```#if devices[idx]['deviceCategory'] == CAMERA_DEVICE_CATEGORY:```

1. I commented out the "follow_move" switch as the Doorbell does not support this functionality. 
  The error is: TypeError: 'NoneType' object is not subscriptable.
  ```#'follow_move': self._switch.get(TYPE_FOLLOW_MOVE)['enable'],```

This is the response for my EZViz DB1 for: GET https://apiieu.ezvizlife.com/v3/userdevices/v1/devices/pagelist?filter=CLOUD
```{"cameraInfos":[{"cameraId":"XXXXXXXXXX","cameraName":"Deurbel","channelNo":1,"cameraCover":"https://ieu.ezvizlife.com/assets/imgs/public/homeDevice.jpeg","deviceSerial":"CXXXXXXX","isShow":1,"videoLevel":1,"videoQualityInfos":[{"streamType":1,"videoLevel":2},{"streamType":1,"videoLevel":1},{"streamType":1,"videoLevel":3}],"streamBizUrl":"biz=1","vtmInfo":{"domain":"vtmuceu.ezvizlife.com","externalIp":"128.1.42.99","internalIp":null,"port":10554,"forceStreamType":0,"isBackup":0},"deviceChannelInfo":{"channelDeviceSerial":null,"channelNo":1,"privacyStatus":0,"powerStatus":0,"globalStatus":0,"signalStatus":1},"cameraShareInfo":null}],"meta":{"code":200,"message":"操作成功","moreInfo":null},"page":{"offset":0,"limit":8,"totalResults":0,"hasNext":false},"deviceInfos":[{"name":"Deurbel","deviceSerial":"CXXXXXX","fullSerial":"CS-DB1-A0-XXXXXXXXXXXXXXXXXXXXXXX","deviceType":"CS-DB1-A0-1B3WPFR","devicePicPrefix":"https://devpic.ezvizlife.com/device/image/CS-DB1-A0-1B3WPFR/","version":"V5.2.4 build 191211","supportExt":"{\"44\":\"0\",\"24\":\"1\",\"46\":\"1\",\"26\":\"0\",\"48\":\"1\",\"28\":\"1\",\"172\":\"1\",\"152\":\"1\",\"154\":\"0\",\"232\":\"1\",\"112\":\"1\",\"233\":\"1\",\"234\":1,\"115\":\"1\",\"118\":\"1\",\"51\":\"0\",\"30\":\"0\",\"31\":\"0\",\"10\":\"1\",\"11\":\"1\",\"12\":\"1\",\"13\":\"3\",\"14\":\"0\",\"15\":\"1\",\"59\":\"1\",\"16\":\"3-4\",\"380\":\"1\",\"141\":\"0\",\"164\":\"1\",\"1\":\"1\",\"2\":\"1\",\"101\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"1\",\"106\":\"2\",\"8\":\"1\",\"9\":\"1\",\"61\":\"0\",\"63\":\"1\",\"42\":\"1\"}","status":1,"userDeviceCreateTime":"2019-09-05 05:07:48","casIp":"eucas.ezvizlife.com","casPort":6500,"channelNumber":1,"hik":false,"deviceCategory":"BDoorBell","deviceSubCategory":"DB1","ezDeviceCapability":"{\"232\":\"0\",\"233\":\"0\",\"234\":1,\"268\":\"1\",\"30\":\"0\",\"31\":\"0\",\"262\":\"0\",\"175\":\"1\"}","customType":"CS-DB1-A0-1B3WPFR","offlineTime":"2020-03-21 16:30:51","offlineNotify":0,"accessPlatform":true,"deviceDomain":"C89135984","instructionBook":"http://devpic.ezvizlife.com/device/image/CS-DB1-A0-1B3WPFR/instruction.jpeg","deviceShareInfo":null}]}```

**Comment by BaQs** [comment]
Really helpfull! Feel free to propose a PR, especially in the pypi package ;)

**Comment by BaQs** [comment]
version 0.1.5.5 should fix this, do you confirm ?

**Comment by GrumpyMeow** [comment]
Hi Pierre,

I tested v0.1.5.5 and did receive an error. On github i suggested a fix
which i tested and gave me a working video output.

**Comment by GrumpyMeow** [comment]
Hi Pierre,

This evening i've put in a Pull Request for a complete list of Device
Switches.
Were you aware of the ability to decompile Android APK files?
There are online APK decompilers available. I;ve user
http://www.javadecompilers.com/apk to get the the Device Switches from the
EZViz Android APK.
Hope this helps...

A next big hurdle is to receive alarm notifications in case of moment...

**Comment by BaQs** [comment]
No I wasn’t. I dont have any android device so I was reverse engineering the IOS app. Using some proxy debugger. Thx for the PR I’ll have a look tonight!

**Comment by fluppie** [comment]
This is my DB1 info (latest EZVIZ firmware from a few days ago)

I have an EZVIZ DB1 doorbell and when I do the login I get:
`'NoneType' object is not subscriptable`

With debug on:
```
 --debug devices status
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): apiieu.ezvizlife.com:443
send: b'POST /v3/users/login HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Type: application/x-www-form-urlencoded\r\nclientType: 1\r\ncustomNo: 1000001\r\nContent-Length: 127\r\n\r\n'
send: b'account=emailaddress%40gmail.com&password=password&featureCode=92c579faa0902cbfcfcc4fc004ef67e7'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Encoding: gzip
header: Content-Type: application/json;charset=UTF-8
header: Date: Sun, 05 Apr 2020 13:45:39 GMT
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 516
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "POST /v3/users/login HTTP/1.1" 200 516
send: b'GET /v3/userdevices/v1/devices/pagelist?filter=CLOUD HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nsessionId: 771cc98034e5484087c4950a0f360cfa\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Encoding: gzip
header: Content-Type: application/json;charset=UTF-8
header: Date: Sun, 05 Apr 2020 13:45:39 GMT
header: ETag: "046845c9fbf2bbe6b78c6aecec702bc7d"
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 991
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "GET /v3/userdevices/v1/devices/pagelist?filter=CLOUD HTTP/1.1" 200 991
send: b'GET /v3/userdevices/v1/devices/pagelist?filter=CLOUD%2CTIME_PLAN%2CCONNECTION%2CSWITCH%2CSTATUS%2CWIFI%2CSTATUS_EXT%2CNODISTURB%2CP2P%2CTTS%2CKMS%2CHIDDNS HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nsessionId: 771cc98034e5484087c4950a0f360cfa\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Encoding: gzip
header: Content-Type: application/json;charset=UTF-8
header: Date: Sun, 05 Apr 2020 13:45:39 GMT
header: ETag: "0579839bead27f1378c7b0a79e1a6227f"
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 2013
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "GET /v3/userdevices/v1/devices/pagelist?filter=CLOUD%2CTIME_PLAN%2CCONNECTION%2CSWITCH%2CSTATUS%2CWIFI%2CSTATUS_EXT%2CNODISTURB%2CP2P%2CTTS%2CKMS%2CHIDDNS HTTP/1.1" 200 2013
send: b'POST /api/device/queryAlgorithmConfig HTTP/1.1\r\nHost: apiieu.ezvizlife.com\r\nUser-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Length: 75\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'subSerial=C72927227&sessionId=771cc98034e5484087c4950a0f360cfa&clientType=1'
reply: 'HTTP/1.1 200 OK\r\n'
header: Access-Control-Allow-Headers: Content-Type, api_key, Authorization
header: Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
header: Access-Control-Allow-Origin: *
header: Content-Encoding: gzip
header: Content-Type: application/json;charset=UTF-8
header: Date: Sun, 05 Apr 2020 13:45:40 GMT
header: Server: Tengine
header: Vary: Accept-Encoding
header: Content-Length: 124
header: Connection: keep-alive
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "POST /api/device/queryAlgorithmConfig HTTP/1.1" 200 124
'NoneType' object is not subscriptable
```

**Comment by GrumpyMeow** [comment]
Hi,

I’m making many improvements on my fork of  pyezviz, which I hope to push
in a few days /weeks.
This should resolve issues and add new functionality.



Op zo 5 apr. 2020 om 15:50 schreef fluppie <notifications@github.com>

**Comment by fluppie** [comment]
OK cool, let me know if you need debug data

**Comment by RenierM26** [comment]
Hi All,

This issue should now be fixed in the last few versions. I'l closing this issue to cleanup the issues list.

You're more than welcome to open a new issue if your're still having difficulty.

**Comment by fluppie** [comment]
Getting the devices status (Python on my Windows laptop) now works for me.
![afbeelding](https://user-images.githubusercontent.com/8402106/107854421-ef20ab00-6e1b-11eb-80d8-d79517c79978.png)
Is the platform in HomeAssistant updated? Or should I side-load something?

**Comment by RenierM26** [comment]
HI @fluppie,

The latest "unofficial" version of the ezviz integration should work. 

Via HACS:
Custom repository : RenierM26/ha-ezviz.

Still busy with the "Official integration". I have an open pull request that needs some work before it's release into the official one.  Mostly things like a new platform for switch statuses and a few changes to the config flow.
