### ISSUE TITLE
Can not login to API EU

### ISSUE THREAD

**Issue by zavertyaev** [BaQs/pyEzviz#38]
DEBUG:urllib3.connectionpool:https://euauth.ezvizlife.com:443 "POST /doLogin HTTP/1.1" 403 118
Can not login to API

**Comment by RenierM26** [comment]
Hi @zavertyaev,

Did you try try the latest version?

**Comment by zavertyaev** [comment]
Successfully installed pyezviz-0.1.8.2
pyezviz -u ... -p ... devices -r us -h
usage: pyezviz devices [-h] {device,status,switch,connection,switch-all}
pyezviz devices: error: argument device_action: invalid choice: 'us' (choose from 'device', 'status', 'switch', 'connection', 'switch-all')

**Comment by RenierM26** [comment]
Hi @zavertyaev,

The syntax is incorrect. Start with the following to get device details

pyezviz -u username@domain.com -p PASS@123 devices status

**Comment by zavertyaev** [comment]
The syntax is from readme.md (Playing with it)

>pyezviz -u username@domain.com -p PASS@123 devices status
...
DEBUG:urllib3.connectionpool:https://apiieu.ezvizlife.com:443 "POST /v3/users/login/v5 HTTP/1.1" 200 87
'loginSession'

**Comment by RenierM26** [comment]
@zavertyaev,

I'm assuming your using your EZVIZ account credentials? What country are you connecting from? I know Russian users need to specify a url when calling the api.

The newest version should report more specific errors for  incorrect credentials.

**Comment by zavertyaev** [comment]
Yeah, Incorrect Username now.
Where I can check credentials? I try to use my password from ezviz studio

**Comment by RenierM26** [comment]
Hi @zavertyaev ,

You need to add the following switch. Ezviz in russia uses an isolated server. apirus.ezvizru.com

pyezviz -u username@domain.com -p PASS@123 -r apirus.ezvizru.com devices status

**Comment by zavertyaev** [comment]
Thanks a lot! it works
