### ISSUE TITLE
Help needed to test mqtt "push notifications"

### ISSUE THREAD

**Issue by RenierM26** [BaQs/pyEzviz#42]
Hi All,

Would you mind testing the MQTT function? Can run it as follows:

python pyezviz -u "username" -p "password" mqtt

**Comment by maxcanna** [comment]
I run the command but I don't know what to expect 🤷🏻 
Here's the output:
```bash
$ python3 pyezviz -u "username" -p "password" mqtt
connected OK Returned code= 0
Subscribed: 1 (2,)
connected OK Returned code= 0
```

**Comment by RenierM26** [comment]
Hi @maxcanna,

Now some event needs to happen. (Motion detection, doorbell push etc.) It should then show info regarding the event. (Device name, event id, pic url etc)

**Comment by maxcanna** [comment]
> Now some event needs to happen. (Motion detection, doorbell push etc.) It should then show info regarding the event. (Device name, event id, pic url etc)

I suspected that, I enabled notification and went in front of the cam but nothing was reported. I'll try again

**Comment by RenierM26** [comment]
Here's an example of what I get:

connected OK Returned code= 0
Subscribed: 1 (2,)
{'id': 146575675675, 'alert': 'Backyard camera 2 Motion Detection Alarm(2021-06-05 10:27:19)', 'ezviz_alert_type': '10002', 'serial': 'E66666', 'msg_time': '2021-06-05 10:27:19', 'img_url': '*****', 'name': 'Backyard c...'}
connected OK Returned code= 0
{'id': 146575675676, 'alert': 'Backyard camera 2 Motion Detection Alarm(2021-06-05 10:29:14)', 'ezviz_alert_type': '10002', 'serial': 'E66666', 'msg_time': '2021-06-05 10:29:14', 'img_url': '*******', 'name': 'Backyard c...'}

**Comment by maxcanna** [comment]
Here's the new output:
```
connected OK Returned code= 0
Subscribed: 1 (2,)
{'id': 1401111977981579264, 'alert': 'Soggiorno PIR Event(2021-06-05 11:41:28)', 'ezviz_alert_type': '10000', 'serial': '---------', 'msg_time': '2021-06-05 11:41:28', 'img_url': '', 'name': 'Soggiorno'}
[Errno 61] Connection refused
```

**Comment by maxcanna** [comment]
BTW Opening the provided image url gives an empty small image

**Comment by GuillaumeNury** [comment]
Hi, I have a similar output :

```
python3@fac2ae2f4405:~/pyEzviz$ python3 pyezviz -u username -p password mqtt
connected OK Returned code= 0
Subscribed: 1 (2,)
connected OK Returned code= 0
connected OK Returned code= 0
{'id': 1404847868600324098, 'alert': 'C6N(SERIAL) Motion Detection Alarm(2021-06-15 19:06:38)', 'ezviz_alert_type': '10002', 'serial': 'SERIAL', 'msg_time': '2021-06-15 19:06:38', 'img_url': 'URL', 'name': 'C6N(F32306...'}
Connection Refused: not authorised.
```

I thought that `not authorised` was due to bad broker credentials, but I have the same error after updating [hard coded credentials](https://github.com/BaQs/pyEzviz/blob/master/pyezviz/mqtt.py#L64).

PS: would love to see these events in HA 😉

**Comment by fab2713** [comment]
Hi, I have the following issue when camera turns off:
```
  File "/home/fabien/dev/venv/ezviz/lib/python3.7/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/home/fabien/dev/venv/ezviz/lib/python3.7/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/fabien/dev/venv/ezviz/lib/python3.7/site-packages/pyezviz/mqtt.py", line 53, in on_message
    "image": mqtt_message["ext"][16],
IndexError: list index out of range
```

Because for this type of event, `ext` has only 15 items instead of 20:
```
{'id': 1234567890123456789, 'alert': 'C3X(SERIAL) Alarme hors ligne', 'ext': ['4', '0', '2022-01-19 08:18:32', '', '', 'BIG_KEY_WITH_SERIAL', '', '', '99', '', '', '0', '', '2105', 'type=30010|dev=SERIAL|pic=0'], 't': 1234567890123, 'sound': 'default.caf', 'badge': 0, 'extras': {'protoVer': '2', 'ticket': 'TICKET_KEY', 'from': 'old', 'serverSdk': '1', 'language': ''}}
```

On the other hand, in the case of an intrusion detection, everything works correctly for me. :)

Thank you for your work

**Comment by x4080** [comment]
@RenierM26 Is mqtt works for newer device ? I have h6c and mqtt seems not working (no notifications or subscribed messages)
