### ISSUE TITLE
Battery Cameras - Working Modes

### ISSUE THREAD

**Issue by uvjim** [BaQs/pyEzviz#44]
Hi,

I recently purchased the BC1C camera.  I noticed that this is picked up by the module with multiple sensors etc being created in Home Assistant.  I'm looking to be able to change the mode that the camera works in.  At first glance the sleep toggle does what I want, however, in the Android app this shows the camera as offline after a period of time (I'm assuming that sleeping the camera also sleeps the Wi-Fi and there for it can't connect again).  I can bring the camera back online by changing the power state (plugging or unplugging the charger from it).  Also, whilst in sleep mode I am unable to view and recorded videos from the device, or change any settings.

There are however Working Modes and one of those appears to do what I need.  The following screenshot shows these in the app.  Is it possible for these to be made available as selectable options in Home Assistant?  Am happy to do some testing if need be.

Thanks in advance.

<img src=https://user-images.githubusercontent.com/8431065/128609686-2e7b1d51-ef96-4cb9-992c-2f35617d171e.png width=50%>

**Comment by uvjim** [comment]
OK. Have tried tonight to find the URL and payloads needed. Unfortunately, every time I try to sniff the traffic using Fiddler or Charles (both on Windows) the ezviz app (on Android) goals to get any network connection so goes no further. I'm unable to find the required URL and payloads to implement this.

If anyone else could take a look that would be great.

Thanks in advance.

**Comment by RenierM26** [comment]
Hi @uvjim,

This is most likely a call to the ezviz CAS server. You'll need to use wireshark to capture the request.

All calls to the ezviz cas server is encrypted so it takes a bit of fiddling to get this to work. I make use of mitmproxy with the setting rawtcp enabled. You'll also need to log the SSL keys in a file and use that in wireshark.

This should decrypt the 1st layer (SSL). Can then see  what the AES128 encrypted string looks like. The ezvizcas file has code to decrcrypt this data by retrieving the decryption keys for your account via an api call. (used for the enable/disable motion detection function)

Apologies for the long explanation but it's quite difficult for me to do without access to the encrypted command string sent.

**Comment by uvjim** [comment]
Thanks. I'll take a look at mitmproxy and see if I can decipher anything.

I'm using the Android app so I'm assuming I just need to configure the Android wireless connection to use mitmproxy as the proxy for the connection.

**Comment by RenierM26** [comment]
Hi @uvjim,

I have added a function to set the battery work mode in the latest pyezviz release.

**Comment by uvjim** [comment]
Thanks @RenierM26 I'll take a look. I assume this will make it through to the Home Assistant integration in due course as well.
