### ISSUE TITLE
Improvment function

### ISSUE THREAD

**Issue by manny73** [BaQs/pyEzviz#6]
Hi,
I have a CS-CV310 CAM
I discoverder a command for enable/disable the siren alarm. I have tested it with a rest tool.
Can you add this functionality, if you think is interesting?
Method POST
URL api/device/sendAlarm
Param 
sessionId : session
enable : 2 on / 1 off
channelNo : 0
type : 1
deviceSerialNo : d123456789

**Comment by RenierM26** [comment]
@manny73,

I have added code for this. Still need to add it in the user front end though.

I'm working on this in issue: #33.
