### ISSUE TITLE
pyEzviz-master>python pyezviz -u *** -p *** devices status

### ISSUE THREAD

**Issue by andreyxc** [BaQs/pyEzviz#88]
pyEzviz-master>python pyezviz -u *** -p *** devices status 

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\korya\Downloads\pyEzviz-master\pyEzviz-master\pyezviz\__main__.py", line 10, in <module>
    from .camera import EzvizCamera
ImportError: attempted relative import with no known parent package

???

**Comment by andreyxc** [comment]
pyEzviz-master>python pyezviz  

tried:

euauth.ezvizlife.com devices status
i.ezvizru.com devices status
apirus.ezvizru.com devices status

**Comment by andrewcoo101** [comment]
To run the scripts from the command line I made these changes:

https://github.com/BaQs/pyEzviz/commit/e914b8c9893824b6690d81359f0f9d253cc4d496

I rarely use python, but these changes / hacks worked for me.

**Comment by andreyxc** [comment]
wow thank you ! works!

**Comment by andreyxc** [comment]
python pyezviz -u *** -p *** -r i.ezvizru.com devices status

**Comment by andreyxc** [comment]
usage: pyezviz [-h] -u USERNAME -p PASSWORD [-r REGION] [--debug] {devices,home_defence_mode,mqtt,camera} ...
pyezviz: error: argument action: invalid choice: 'XXXXXXX' (choose from 'devices', 'home_defence_mode', 'mqtt', 'camera')???

python pyezviz -u XXX -p XXX -r i.ezvizru.com --serial XXXX

**Comment by andreyxc** [comment]
python pyezviz -u XXXX -p XXXX -r i.ezvizru.com camera --serial XXXX status  -wow thank you ! works!
