### ISSUE TITLE
Trigger Light

### ISSUE THREAD

**Issue by zaimzazali** [BaQs/pyEzviz#91]
Heyya..

I am currently using EZVIZ LC3..
Just wondering if I could get the human-shaped trigger flag and then set the light to light up by using this package?

**Comment by RenierM26** [comment]
Hi @zaimzazali,

It's implemented in the Home Assistant as far as can be done from the current EZVIZ API data. 

- Swich for Motion activated light.
- Light entity to turn the light on/off manually.
- Status if light was manually activated. (The api doesn't return a on status if it was triggered via the PIR sensor)
